// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: proto/lamportClocks.proto

package lamportClocks_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type MessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action     string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	AccountNum int64  `protobuf:"varint,5,opt,name=accountNum,proto3" json:"accountNum,omitempty"`
	T          int64  `protobuf:"varint,3,opt,name=t,proto3" json:"t,omitempty"`
	Amount     int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lamportClocks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lamportClocks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_lamportClocks_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MessageRequest) GetAccountNum() int64 {
	if x != nil {
		return x.AccountNum
	}
	return 0
}

func (x *MessageRequest) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *MessageRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// The response message containing the greetings
type MessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack               string `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	T                 int64  `protobuf:"varint,2,opt,name=t,proto3" json:"t,omitempty"`
	OtherNodeDoneFlag bool   `protobuf:"varint,3,opt,name=otherNodeDoneFlag,proto3" json:"otherNodeDoneFlag,omitempty"`
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lamportClocks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lamportClocks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_lamportClocks_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

func (x *MessageResponse) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *MessageResponse) GetOtherNodeDoneFlag() bool {
	if x != nil {
		return x.OtherNodeDoneFlag
	}
	return false
}

var File_proto_lamportClocks_proto protoreflect.FileDescriptor

var file_proto_lamportClocks_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c, 0x61, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x6e, 0x0a, 0x0e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e,
	0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4e, 0x75, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5f, 0x0a, 0x0f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12,
	0x0c, 0x0a, 0x01, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x74, 0x12, 0x2c, 0x0a,
	0x11, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x46, 0x6c,
	0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4e,
	0x6f, 0x64, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x32, 0x60, 0x0a, 0x0e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x6c,
	0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6c, 0x61,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x63, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6c, 0x61, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lamportClocks_proto_rawDescOnce sync.Once
	file_proto_lamportClocks_proto_rawDescData = file_proto_lamportClocks_proto_rawDesc
)

func file_proto_lamportClocks_proto_rawDescGZIP() []byte {
	file_proto_lamportClocks_proto_rawDescOnce.Do(func() {
		file_proto_lamportClocks_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lamportClocks_proto_rawDescData)
	})
	return file_proto_lamportClocks_proto_rawDescData
}

var file_proto_lamportClocks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lamportClocks_proto_goTypes = []interface{}{
	(*MessageRequest)(nil),  // 0: lamportClocks.MessageRequest
	(*MessageResponse)(nil), // 1: lamportClocks.MessageResponse
}
var file_proto_lamportClocks_proto_depIdxs = []int32{
	0, // 0: lamportClocks.MessageService.SendMessage:input_type -> lamportClocks.MessageRequest
	1, // 1: lamportClocks.MessageService.SendMessage:output_type -> lamportClocks.MessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lamportClocks_proto_init() }
func file_proto_lamportClocks_proto_init() {
	if File_proto_lamportClocks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lamportClocks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lamportClocks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lamportClocks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lamportClocks_proto_goTypes,
		DependencyIndexes: file_proto_lamportClocks_proto_depIdxs,
		MessageInfos:      file_proto_lamportClocks_proto_msgTypes,
	}.Build()
	File_proto_lamportClocks_proto = out.File
	file_proto_lamportClocks_proto_rawDesc = nil
	file_proto_lamportClocks_proto_goTypes = nil
	file_proto_lamportClocks_proto_depIdxs = nil
}
